name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.0
      - name: Setup haxe
        run: |
          haxe --version
          haxelib dev three.hx .
      - name: Build haxedoc.xml
        run: |
          haxe haxedoc.hxml
      - name: Build examples
        run: |
          haxe --cwd examples/basic build.hxml
